version: '2.1'  

jobs:
  build:
    docker:
      - image: node:18  # Example Docker image, adjust as needed
    steps:
      - checkout  # Pulls the source code

      - setup_node:
          name: Set Up Node.js
          command: |
            nvm install 14  # Install Node.js version 14
            nvm use 14
            npm install -g npm@latest  # Update npm to the latest version

      - install_dependencies:
          name: Install Dependencies
          command: npm ci  # Clean install dependencies

      - build:
          name: Build the Project
          command: npm run build --if-present  # Build if a build script is present

      - test:
          name: Run Tests
          command: npm test  # Run the tests

    # Optional: Caching
    caches:
      - npm  # Cache npm dependencies to speed up builds


    # Optional: Matrix for multiple Node.js versions
    matrix:
      node-version:
        - 14
        - 16
        - 18
      steps:
        - checkout
        - setup_node:
            name: Set Up Node.js ${{ node-version }}
            command: |
              nvm install ${{ node-version }}
              nvm use ${{ node-version }}
        - install_dependencies
        - build
        - test
